---

- hosts: cloudengine
  gather_facts: no
  vars:
    trunk_id: 100
    all_members: '40GE 2/0/24,40GE 2/0/25'
    clear_cmd: 'interface 40GE 2/0/24, clear config this, quit, interface 40GE 2/0/25, clear config this, quit'
  
  tasks:
  - ce_config: lines={{clear_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_eth_trunk: trunk_id={{trunk_id}} mode=manual members={{all_members}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: lines={{clear_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
