---

- hosts: ce128
  gather_facts: no
  tasks:
  - ce_evpn_bgp: bgp_instance=100 peer_address=1.1.1.1 as_number=100 peer_enable=true host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_evpn_bgp: bgp_instance=100 peer_address=1.1.1.1 as_number=100 peer_enable=false host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_evpn_bgp: bgp_instance=100 peer_group_name=aaa advertise_router_type=irb state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_evpn_bgp: bgp_instance=100 peer_group_name=aaa advertise_router_type=irb state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_evpn_bgp: bgp_instance=100 vpn_name=aaa advertise_l2vpn_evpn=true host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_evpn_bgp: bgp_instance=100 vpn_name=aaa advertise_l2vpn_evpn=false host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}