---

- hosts: cloudengine
  gather_facts: no
  vars:
    test_intf: 40ge2/0/30
    process: 10
    clear_cmd: 'interface 40ge2/0/30, clear config this'
    setup_cmd: 'interface 40ge2/0/30, undo portswitch'

  tasks:
  - ce_config: lines={{clear_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: lines={{setup_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_interface_ospf: process_id={{process}} area=100 interface={{test_intf}} state=present cost=10 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
 
  - ce_interface_ospf: process_id={{process}} area=100 interface={{test_intf}} state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
 
  - ce_ospf: process_id={{process}} state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: lines={{clear_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}