---

- hosts: cloudengine
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:

  - ce_evpn_global: evpn_overlay_enable=enable provider="{{ cli }}"
  - ce_evpn_global: evpn_overlay_enable=disable provider="{{ cli }}"