---

- hosts: cloudengine
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli
  tasks:  
  - ce_netstream_export:  type=ip source_ip=192.8.2.2 provider="{{ cli }}"
  - ce_netstream_export:  type=vxlan source_ip=192.8.2.3 provider="{{ cli }}"
  - ce_netstream_export:  type=ip host_ip=192.8.2.4 host_port=25 host_vpn=test provider="{{ cli }}"
  - ce_netstream_export:  type=vxlan host_ip=192.8.2.5 host_port=26 host_vpn=test provider="{{ cli }}"
  - ce_netstream_export:  type=ip version=9 as_option=origin bgp_nexthop=enable provider="{{ cli }}"
  - ce_netstream_export:  type=vxlan version=9 provider="{{ cli }}"