---

- hosts: cloudengine
  gather_facts: no
  vars:
    test_range: "2-10,20,50,55-60,100-150"
    test_vlan: 50
  
  tasks:  
  - ce_vlan: vlan_range={{test_range}} state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vlan: vlan_id={{test_vlan}} name="WEB" host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vlan: vlan_id={{test_vlan}} state="absent" host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}