---

- hosts: cloudengine
  gather_facts: no
  vars:
  
  tasks:  
  - ce_file_copy: local_file=/usr/zzj.cfg remote_file=/zzj.cfg file_system='flash:' host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}