---

- hosts: cloudengine
  gather_facts: no
  vars:
    test_intf: 40GE2/0/22
    clear_cmd: 'interface 40ge2/0/22, clear config this'
    setup_cmd: 'vlan batch 10 20'

  tasks:
  - ce_config: lines={{clear_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: lines={{setup_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_switchport: interface={{test_intf}} state=unconfigured host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_switchport: interface={{test_intf}} mode=access access_vlan=20 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_switchport: interface={{test_intf}} mode=trunk native_vlan=10 trunk_vlans=5-10 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_switchport: interface={{test_intf}} mode=trunk native_vlan=10 trunk_vlans=2-50 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_switchport: interface={{test_intf}} mode=trunk trunk_vlans=51-4000  state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: lines={{clear_cmd}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}