---

- hosts: cloudengine
  gather_facts: no
  vars:

  tasks:

  - ce_evpn_global: evpn_overlay_enable=true host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_evpn_global: evpn_overlay_enable=false host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}