---

- hosts: cloudengine
  gather_facts: no
  
  tasks:

  - ce_ns_aging: active_interval=40 active_mode=ip active_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: active_interval=40 active_mode=vxlan active_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: active_mode=ip active_state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: active_interval=40 active_mode=vxlan active_state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: active_interval=30 active_mode=ip active_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: active_interval=30 active_mode=vxlan active_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: inactive_interval=300 inactive_mode=ip inactive_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: inactive_interval=300 inactive_mode=vxlan inactive_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: inactive_mode=ip inactive_state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: inactive_interval=300 inactive_mode=vxlan inactive_state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: inactive_interval=30 inactive_mode=ip inactive_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: inactive_interval=30 inactive_mode=vxlan inactive_state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: tcp_timeout=enable tcp_mode=vxlan host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: tcp_timeout=enable tcp_mode=ip host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ns_aging: tcp_timeout=disable tcp_mode=ip host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
