---

- hosts: cloudengine
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:

  - ce_evpn_bgp_rr: as_number=20 bgp_evpn_enable=enable provider="{{ cli }}"
  - ce_evpn_bgp_rr: as_number=20 peer_type=ipv4_address peer=192.8.3.3 reflect_client=enable provider="{{ cli }}"
  - ce_evpn_bgp_rr: as_number=20 policy_vpn_target=enable provider="{{ cli }}"
  - ce_evpn_bgp_rr: as_number=20 bgp_evpn_enable=enable peer_type=ipv4_address peer=192.8.3.3 reflect_client=enable policy_vpn_target=disable provider="{{ cli }}"