---

- hosts: cloudengine
  gather_facts: no
  vars:
      cli:
        host: "{{ inventory_hostname }}"
        port: "{{ ansible_ssh_port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli
  
  tasks:  
  - ce_dldp: enable=enable provider="{{ cli }}"
  - ce_dldp: work_mode=normal provider="{{ cli }}"
  - ce_dldp: time_interval=6 provider="{{ cli }}"
  - ce_dldp: reset=enable provider="{{ cli }}"
  - ce_dldp: auth_mode=md5 auth_pwd=abc provider="{{ cli }}"
  - ce_dldp: enable=enable work_mode=normal time_interval=6 reset=enable auth_mode=md5 auth_pwd=abc provider="{{ cli }}"
  - ce_dldp: enable=disable provider="{{ cli }}"
