---

- hosts: ce78
  gather_facts: no
  vars:
    username: rootDC
    password: Admin@123
  
  tasks:  
  - ce_vlan: vlan_range="2-10,20,50,55-60,100-150" state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vlan: vlan_id="50" name="WEB" host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vlan: vlan_id="50" state="absent" host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}