---

- name: cloudengine info center log module test
  hosts: cloudengine
  gather_facts: no

  tasks:

  - ce_info_center_log: log_time_stamp=date_boot state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_info_center_log: log_time_stamp=date_tenthsecond state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_info_center_log: log_time_stamp=shortdate_second state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_info_center_log: log_time_stamp=formatdate_millisecond state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_info_center_log: log_time_stamp=formatdate_millisecond state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_info_center_log: log_buff_enable=false state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_info_center_log: log_buff_enable=true state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_info_center_log: log_buff_size=100 state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_info_center_log: log_buff_size=100 state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_info_center_log: module_name=aaa channel_id=1 log_enable=true state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_info_center_log: module_name=aaa channel_id=1 log_enable=true log_level=notification state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_info_center_log: module_name=aaa channel_id=1 log_enable=true log_level=notification state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
