---

- name: cloudengine vrf module test
  hosts: Boardleaf1
  connection: local
  gather_facts: no

  tasks:
  - ce_vrf_af: vrf=vpna vrf_aftype=v4 state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 vpn_target_type=export_extcommunity vpn_target_value=2:2 vpn_target_state=present state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 vpn_target_type=export_extcommunity vpn_target_value=2:2 vpn_target_state=absent state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 vpn_target_type=import_extcommunity vpn_target_value=3:3 vpn_target_state=present state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 vpn_target_type=import_extcommunity vpn_target_value=3:3 vpn_target_state=absent state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 vpn_target_type=import_extcommunity vpn_target_value=3:3 vpn_target_state=present state=present host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_vrf_af: vrf=vpna vrf_aftype=v4 route_distinguisher=1:1 vpn_target_type=import_extcommunity vpn_target_value=3:3 vpn_target_state=absent state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
