---

- hosts: cloudengine
  gather_facts: no
  vars:
      test_intf: 40GE1/0/22
      cli:
        host: "{{ inventory_hostname }}"
        port: "{{ ansible_ssh_port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli
  tasks:  
  - ce_vrf_interface: vpn_interface={{test_intf}} vrf=jss  provider="{{ cli }}"
  - ce_vrf_interface: vpn_interface={{test_intf}} vrf=jss  state=absent provider="{{ cli }}"
