---

- hosts: ce78
  gather_facts: no
  
  tasks:
  - ce_aaa_server: host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}} state=present acct_scheme_name=test1  accounting_mode=hwtacacs hwtacas_template=test2 group_name=wdz

  - ce_aaa_server: host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}} state=absent acct_scheme_name=test1  accounting_mode=hwtacacs hwtacas_template=test2 group_name=wdz
