---

- hosts: cloudengine
  gather_facts: no
  vars:
  
  tasks:  
  - ce_dldp: enable=true host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_dldp: work_mode=normal host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_dldp: time_interval=6 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_dldp: reset=true host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_dldp: auth_mode=md5 auth_pwd=abc host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_dldp: enable=true work_mode=normal time_interval=6 reset=true auth_mode=md5 auth_pwd=abc host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  - ce_dldp: enable=false host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
