---

- hosts: ce78
  gather_facts: no
  vars:
    username: rootDC
    password: Admin@123
    trunk_id: 100
    all_members: '40GE 2/0/24,40GE 2/0/25'
  
  tasks:  
  - ce_eth_trunk: trunk_id={{trunk_id}} mode=manual members={{all_members}} host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
