---

- name: cloudengine ospf vrf module test
  hosts: Boardleaf1
  connection: local
  gather_facts: no

  tasks:
  - ce_ospf_vrf: ospf=2 route_id=2.2.2.2 description=test host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 route_id=2.2.2.2 description=test host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 bandwidth=300 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 bandwidth=100 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 lsaAlFlag=true lsaAInterval=100 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 lsaAMaxInterval=800 lsaAStartInterval=400 lsaAHoldInterval=400 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 lsaAMaxInterval=800 lsaAStartInterval=400 lsaAHoldInterval=400 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 lsaOInterval=4 lsaOMaxInterval=4000 lsaOStartInterval=400 lsaOHoldInterval=800 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 spfIntervalType=timer spfInterval=4 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}


  - ce_ospf_vrf: ospf=2 spfIntervalType=millisecond spfIntervalMi=400 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_ospf_vrf: ospf=2 spfIntervalType=intelligent-timer spfMaxInterval=8000 spfStartInterval=400 spfHoldInterval=800 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
