---

- name: cloudengine command module test
  hosts: cloudengine
  gather_facts: no

  tasks:
  - ce_command: commands='display device' host={{inventory_hostname}} username={{username}} password={{password}}

  - ce_command: commands='display device, display version' host={{inventory_hostname}} username={{username}} password={{password}}

  - ce_command: commands='display interface' host={{inventory_hostname}} username={{username}} password={{password}}

  - ce_command: commands='display device, display version, display interface' host={{inventory_hostname}} username={{username}} password={{password}}