---

- hosts: ce78
  gather_facts: no
  vars:
    username: rootDC
    password: Admin@123
    process: 10
  
  tasks:  
  - ce_interface_ospf: process_id={{process}} area=100 interface=40ge2/0/30 state=present cost=10 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
 
  - ce_interface_ospf: process_id={{process}} area=100 interface=40ge2/0/30 state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
 
  - ce_ospf: process_id={{process}} state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}