---

- hosts: ce78
  gather_facts: no
  vars:
    username: rootDC
    password: Admin@123
  
  tasks:
  - ce_config: lines='sysname {{ inventory_hostname }}' host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: before='undo acl 2000' parents='acl 2000' lines='rule 10 permit source 1.1.1.1 32,rule 20 permit source 2.2.2.2 32,rule 30 permit source 3.3.3.3 32,rule 40 permit source 4.4.4.4 32,rule 50 permit source 5.5.5.5 32' match=exact host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_config: before='undo acl 2000' parents='acl 2000' lines='rule 10 permit source 1.1.1.1 32,rule 20 permit source 2.2.2.2 32,rule 30 permit source 3.3.3.3 32,rule 40 permit source 4.4.4.4 32' replace=block host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}