---

- hosts: ce78
  gather_facts: no
  vars:
  
  tasks:  
  - ce_switchport: interface=40GE1/0/22 state=unconfigured host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_switchport: interface=40GE1/0/22 mode=access access_vlan=20 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}

  - ce_switchport: interface=40GE1/0/22 mode=trunk native_vlan=10 trunk_vlans=5-10 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_switchport: interface=40GE1/0/22 mode=trunk native_vlan=10 trunk_vlans=2-50 host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}
  
  - ce_switchport: interface=40GE1/0/22 mode=trunk trunk_vlans=51-4000  state=absent host={{inventory_hostname}} username={{username}} password={{password}} port={{ansible_ssh_port}}